[package]
name = "hola_mundo"
version = "0.1.0"
authors = ["Amanda Iniesta Sep√∫lveda <theamandable@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.3"
